# Generated by Django 4.2.30 on 2026-04-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_group_lesson_start_time_group_schedule_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='lesson_end_time',
            field=models.TimeField(default='11:30'),
        ),
        migrations.AlterField(
            model_name='group',
            name='schedule_type',
            field=models.CharField(choices=[('3_days_toq', 'Haftada 3 kun (Toq kunlar)'), ('3_days_juft', 'Haftada 3 kun (Juft kunlar)'), ('5_days', 'Haftada 5 kun'), ('daily', 'Har kuni')], default='3_days_toq', max_length=20),
        ),
    ]
