# Generated by Django 4.2.30 on 2026-04-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('lesson_added', 'Lesson'), ('test_started', 'Test'), ('payment_reminder', 'Payment'), ('announcement', 'Announcement'), ('lesson_reminder', 'Dars Eslatmasi'), ('chat_message', 'Chat Xabari')], max_length=30),
        ),
    ]
